#![warn(missing_docs)]

//! A simple to use BPS, IPS and UPS patching library

use std::{
    error,
    fmt::{Debug, Display},
    fs::File,
    io, result,
    string::FromUtf8Error,
};

use byteorder::ReadBytesExt;
use crc::{CRC_32_ISO_HDLC, Crc};

/// BPS ('Beat Patch') file routines
pub mod bps;
/// BPS ('International Patching System') file routines
pub mod ips;
/// UPS file routines
pub mod ups;

const INLINE_DATA_SIZE: usize = 16;
static CRC32: Crc<u32> = Crc::<u32>::new(&CRC_32_ISO_HDLC);

#[cfg(test)]
mod tests;

/// Alias for `std::result::Result<T, Error>`
pub type Result<T> = result::Result<T, Error>;

#[allow(non_camel_case_types)]
type uvar = u128;

/// Generic type for any patch file
pub trait PatchFile: Sized {
    /// Type of individual patch records
    type Record;

    /// Create a `PatchFile` from a `File`
    /// # Errors
    /// Any `Error` except `InvalidOutputChecksum` and `InvalidOutputFilesize`
    fn parse(patch: &File) -> Result<Self>;

    /// Apply the contained records to an input `File` and generate a patched `File`
    /// # Errors
    /// Any `Error`
    fn apply(&self, input: &File, output: &mut File) -> Result<()>;

    /// Inspect the records contained in this `PatchFile`
    fn records(&self) -> impl Iterator<Item = &Self::Record>;
}

trait UvarReadExtensions {
    fn read_uvar(&mut self) -> io::Result<uvar>;
}

impl<T: io::Read> UvarReadExtensions for T {
    fn read_uvar(&mut self) -> io::Result<uvar> {
        let mut result = 0;
        let mut shift = 0;
        loop {
            let octet = self.read_u8()?;
            if 0 != octet & 0x80 {
                result += uvar::from(octet & 0x7F) << shift;
                break;
            }
            result += uvar::from(octet | 0x80) << shift;
            shift += 7;
        }
        Ok(result)
    }
}

/// Represents all possible errors generated by the library
#[derive(Debug)]
#[non_exhaustive]
pub enum Error {
    /// The patch file header was not valid.
    InvalidHeader,
    /// The input file was not valid because the checksum was wrong.
    #[allow(missing_docs)]
    InvalidInputChecksum { expected: u32, actual: u32 },
    /// The input file was not valid because the size was wrong.
    #[allow(missing_docs)]
    InvalidInputSize { expected: u64, actual: u64 },
    /// The patch metadata could not be represented as UTF-8.
    InvalidMetadata(FromUtf8Error),
    /// The out file was not valid because the checksum was wrong. This indicates an error with the patch file.
    #[allow(missing_docs)]
    InvalidOutputChecksum { expected: u32, actual: u32 },
    /// The out file was not valid because the size was wrong. This indicates an error with the patch file.
    #[allow(missing_docs)]
    InvalidOutputSize { expected: u64, actual: u64 },
    /// I/O error
    IO(io::Error),
    /// An offset overflows. The contained string hints at the logical meaning of the invalid offset.
    OffsetOverflow(&'static str),
    /// A variable length integer could not be represented as a 128-bit integer. The contained string hints at the logical meaning of the invalid integer.
    VariableIntegerOverflow(&'static str),
    /// The patch contains a record with no data. This indicates an error with the patch file.
    ZeroSizedHunk,
}

impl Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::InvalidHeader => write!(f, "Patch header invalid"),
            Error::InvalidInputChecksum { expected, actual } => write!(
                f,
                "Input checksum invalid; expected: {expected:x}, Actual: {actual:x}"
            ),
            Error::InvalidInputSize { expected, actual } => write!(
                f,
                "Input size invalid; Expected: {expected}, Actual: {actual}"
            ),
            Error::InvalidMetadata(inner) => write!(f, "Metadata is not valid \"{inner}\""),
            Error::InvalidOutputChecksum { expected, actual } => write!(
                f,
                "Output checksum invalid; expected: {expected:x}, Actual: {actual:x}"
            ),
            Error::InvalidOutputSize { expected, actual } => write!(
                f,
                "Output size invalid; Expected: {expected}, Actual: {actual}"
            ),
            Error::IO(inner) => write!(f, "I/O error \"{inner}\""),
            Error::OffsetOverflow(what) => {
                write!(f, "A file offset integer for '{what}' overflowed")
            }
            Error::VariableIntegerOverflow(what) => write!(
                f,
                "A variable-length integer for '{what}' could not be represented"
            ),
            Error::ZeroSizedHunk => write!(f, "A patch hunk was zero-sized"),
        }
    }
}

impl error::Error for Error {
    fn source(&self) -> Option<&(dyn error::Error + 'static)> {
        match self {
            Error::InvalidMetadata(inner) => Some(inner),
            Error::IO(inner) => Some(inner),
            _ => None,
        }
    }
}

impl From<io::Error> for Error {
    fn from(value: io::Error) -> Self {
        Error::IO(value)
    }
}

fn crc32<T: io::Read>(data: T) -> io::Result<u32> {
    crc32_length(data, None)
}

fn crc32_length<T: io::Read>(mut data: T, length: Option<u64>) -> io::Result<u32> {
    let mut digest = CRC32.digest();
    let mut buf = [0; 4096];
    let mut total_bytes = 0;
    loop {
        let mut bytes = data.read(&mut buf)?;
        if bytes > 0 {
            total_bytes += bytes as u64;
            let early_done = if let Some(length) = length
                && total_bytes > length
            {
                bytes -= usize::try_from(total_bytes - length).expect("crc32 length overflow");
                true
            } else {
                false
            };

            digest.update(&buf[..bytes]);

            if early_done {
                break;
            }
        } else {
            break;
        }
    }
    Ok(digest.finalize())
}
